services:
  explorer_service:
    image: lssa/explorer_service
    build:
      context: ..
      dockerfile: explorer_service/Dockerfile
    container_name: explorer_service
    environment:
      INDEXER_RPC_URL: ${INDEXER_RPC_URL:-http://localhost:8779}
    ports:
      - "8080:8080"
