[package]
name = "wallet-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
wallet.workspace = true
nssa.workspace = true
common.workspace = true
tokio.workspace = true

[build-dependencies]
cbindgen = "0.26"
