[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true
nssa_core.workspace = true
nssa.workspace = true

thiserror.workspace = true
borsh.workspace = true
rocksdb.workspace = true
