[package]
name = "programs"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[dependencies]
nssa_core.workspace = true

risc0-zkvm.workspace = true
serde = { workspace = true, default-features = false }
