[package]
name = "bedrock_client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest.workspace = true
anyhow.workspace = true
logos-blockchain-common-http-client.workspace = true
logos-blockchain-core.workspace = true
