[package]
name = "bedrock_client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest.workspace = true
anyhow.workspace = true
serde.workspace = true
log.workspace = true
thiserror.workspace = true
url.workspace = true
futures.workspace = true
serde_json.workspace = true
const-hex.workspace = true
serde_with.workspace = true
ed25519-dalek                = { workspace = true, features = ["rand_core", "serde", "zeroize"] }
